server:
  port: 3356
spring:
  application:
    name: cloud-config-client-3356
  consul:
    host: localhost
    port: 8500
    discovery:
      service-name: cloud-config-client
      instance-id: ${spring.application.name}
config:
  info: application-prod.version=2
  msg: application-prod.msg=test2
